### ISSUE TITLE
Can UTopia be applied to C++ projects that do not use a testing framework?

### ISSUE THREAD

**Issue by ShilngYu** [Samsung/UTopia#33]
Hello, I am using UTopia to test other C++ projects, but the C++ project does not use frameworks such as GoogleTest for unit testing. Can UTopia perform normal testing on such projects?
If testing is possible, how does it compare to projects with a testing framework?

**Comment by yuweol** [comment]
I'm sorry to late.
Currently UTopia supports google test and boost test. 
So if that framework is not one of the above, It is impossible to apply UTopia.

Although we designed UTopia to add other testing framework easily,
\however it may not be easy because documentation for it is not enough :(

If you want to do it, we can prepare documentation, but it may take some times.

Again, sorry to late answer.

**Comment by ShilngYu** [comment]
Thanks for looking this issue!
